name: Install dependencies
description: Setup working Python environment with dependencies installed

inputs:
  python-version:
    required: true
    description: The version of Python to use (from actions/setup-python@v4)

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
